<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
    <UserSecretsId>d0d27b16-837d-48cf-a7b5-e91cf0b42e5d</UserSecretsId>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591;1573</NoWarn>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="MassTransit" Version="8.2.5" />
	  <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.19" />
	  <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.19" />

	  <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />

	  <PackageReference Include="MongoDB.EntityFrameworkCore" Version="8.4.0" />

	  <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />

	  <PackageReference Include="Serilog.Sinks.Grafana.Loki" Version="8.3.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
