from __future__ import annotations

from typing import Protocol, Sequence

from lessley_deals.domain.models import (
    CanonicalStore,
    Club,
    CurrentDeal,
    Deal,
    DealVersion,
    ExternalReference,
    MatchVerdict,
    NormalizedRecord,
    RawScrapedRecord,
    RawStore,
    ReviewItem,
    StoreAlias,
)


# ---------------------------------------------------------------------------
# Repository protocols
# ---------------------------------------------------------------------------

class RawStoreRepository(Protocol):
    def save(self, store: RawStore) -> None: ...
    def save_many(self, stores: Sequence[RawStore]) -> None: ...
    def exists_by_fingerprint(self, fingerprint: str) -> bool: ...
    def get_all(self) -> list[RawStore]: ...
    def get_by_source(self, source_id: str) -> list[RawStore]: ...


class RawDealRepository(Protocol):
    def save(self, record: RawScrapedRecord) -> None: ...
    def save_many(self, records: Sequence[RawScrapedRecord]) -> None: ...
    def exists_by_fingerprint(self, fingerprint: str) -> bool: ...
    def get_by_id(self, record_id: str) -> RawScrapedRecord | None: ...
    def get_all(self) -> list[RawScrapedRecord]: ...
    def get_by_source(self, source_id: str) -> list[RawScrapedRecord]: ...


class CanonicalStoreRepository(Protocol):
    def save(self, store: CanonicalStore) -> None: ...
    def get_by_id(self, store_id: str) -> CanonicalStore | None: ...
    def get_all(self) -> list[CanonicalStore]: ...
    def search(self, query: str) -> list[CanonicalStore]: ...


class AliasRepository(Protocol):
    def save(self, alias: StoreAlias) -> None: ...
    def find_by_alias(self, alias: str) -> StoreAlias | None: ...
    def get_all(self) -> list[StoreAlias]: ...
    def get_by_store(self, store_id: str) -> list[StoreAlias]: ...
    def delete(self, alias_id: str) -> None: ...


class ClubRepository(Protocol):
    def save(self, club: Club) -> None: ...
    def get_by_id(self, club_id: str) -> Club | None: ...
    def get_by_source(self, source_id: str) -> Club | None: ...
    def get_all(self) -> list[Club]: ...


class ExternalRefRepository(Protocol):
    def save(self, ref: ExternalReference) -> None: ...
    def get_by_store(self, store_id: str) -> list[ExternalReference]: ...
    def get_by_system(self, system: str) -> list[ExternalReference]: ...
    def delete(self, ref_id: str) -> None: ...


class DealRepository(Protocol):
    def save(self, deal: Deal) -> None: ...
    def exists_by_fingerprint(self, fingerprint: str) -> bool: ...
    def get_by_store(self, store_id: str) -> list[Deal]: ...
    def get_all(self) -> list[Deal]: ...


class DealVersionRepository(Protocol):
    """Append-only SCD Type 2 history of deals."""

    def append_many(self, versions: Sequence[DealVersion]) -> None: ...

    def close_current(self, closures: Sequence[tuple[str, object]]) -> None:
        """Close the current row of each ``deal_key``: ``(deal_key, valid_to)``.

        The row stops being current and gains an end date.  Its ``status`` is
        left untouched — it records what the deal *was* during that window, and
        point-in-time queries depend on that staying true.

        Idempotent: closing an already-closed row is a no-op, which makes a
        crashed run safe to replay.
        """
        ...

    def get_current(self, deal_key: str) -> DealVersion | None: ...
    def get_history(self, deal_key: str) -> list[DealVersion]: ...
    def next_version(self, deal_key: str) -> int: ...


class CurrentDealRepository(Protocol):
    """Head table — one row per business key, always the latest state."""

    def bulk_upsert(self, heads: Sequence[CurrentDeal]) -> None: ...
    def get(self, deal_key: str) -> CurrentDeal | None: ...
    def get_by_source(self, source_id: str) -> list[CurrentDeal]: ...
    def get_active(self, store_id: str | None = None) -> list[CurrentDeal]: ...
    def count_active(self, source_id: str) -> int: ...


class ReviewRepository(Protocol):
    def save(self, item: ReviewItem) -> None: ...
    def get_by_id(self, item_id: str) -> ReviewItem | None: ...
    def get_pending(self) -> list[ReviewItem]: ...
    def get_all(self) -> list[ReviewItem]: ...
    def update(self, item: ReviewItem) -> None: ...


# ---------------------------------------------------------------------------
# Scraping protocols
# ---------------------------------------------------------------------------

class SourceScraper(Protocol):
    @property
    def source_id(self) -> str: ...
    async def scrape(self) -> tuple[list[RawStore], list[RawScrapedRecord]]: ...


# ---------------------------------------------------------------------------
# Normalization protocols
# ---------------------------------------------------------------------------

class NormalizationStep(Protocol):
    def apply(self, store_name: str, deal_description: str) -> tuple[str, str]:
        """Return (processed_store_name, processed_deal_description)."""
        ...


# ---------------------------------------------------------------------------
# Matching protocols
# ---------------------------------------------------------------------------

class MatchStage(Protocol):
    @property
    def name(self) -> str: ...

    def match(
        self,
        normalized: NormalizedRecord,
        aliases: list[StoreAlias],
        stores: list[CanonicalStore],
    ) -> MatchVerdict | None:
        """Return a verdict if this stage can decide, else None to continue."""
        ...
