from __future__ import annotations

from typing import Protocol, Sequence

from lessley_deals.domain.models import (
    CanonicalStore,
    Deal,
    ExternalReference,
    MatchVerdict,
    NormalizedRecord,
    RawScrapedRecord,
    RawStore,
    ReviewItem,
    StoreAlias,
)


# ---------------------------------------------------------------------------
# Repository protocols
# ---------------------------------------------------------------------------

class RawStoreRepository(Protocol):
    def save(self, store: RawStore) -> None: ...
    def save_many(self, stores: Sequence[RawStore]) -> None: ...
    def exists_by_fingerprint(self, fingerprint: str) -> bool: ...
    def get_all(self) -> list[RawStore]: ...
    def get_by_source(self, source_id: str) -> list[RawStore]: ...


class RawDealRepository(Protocol):
    def save(self, record: RawScrapedRecord) -> None: ...
    def save_many(self, records: Sequence[RawScrapedRecord]) -> None: ...
    def exists_by_fingerprint(self, fingerprint: str) -> bool: ...
    def get_by_id(self, record_id: str) -> RawScrapedRecord | None: ...
    def get_all(self) -> list[RawScrapedRecord]: ...
    def get_by_source(self, source_id: str) -> list[RawScrapedRecord]: ...


class CanonicalStoreRepository(Protocol):
    def save(self, store: CanonicalStore) -> None: ...
    def get_by_id(self, store_id: str) -> CanonicalStore | None: ...
    def get_all(self) -> list[CanonicalStore]: ...
    def search(self, query: str) -> list[CanonicalStore]: ...


class AliasRepository(Protocol):
    def save(self, alias: StoreAlias) -> None: ...
    def find_by_alias(self, alias: str) -> StoreAlias | None: ...
    def get_all(self) -> list[StoreAlias]: ...
    def get_by_store(self, store_id: str) -> list[StoreAlias]: ...
    def delete(self, alias_id: str) -> None: ...


class ExternalRefRepository(Protocol):
    def save(self, ref: ExternalReference) -> None: ...
    def get_by_store(self, store_id: str) -> list[ExternalReference]: ...
    def get_by_system(self, system: str) -> list[ExternalReference]: ...
    def delete(self, ref_id: str) -> None: ...


class DealRepository(Protocol):
    def save(self, deal: Deal) -> None: ...
    def exists_by_fingerprint(self, fingerprint: str) -> bool: ...
    def get_by_store(self, store_id: str) -> list[Deal]: ...
    def get_all(self) -> list[Deal]: ...


class ReviewRepository(Protocol):
    def save(self, item: ReviewItem) -> None: ...
    def get_by_id(self, item_id: str) -> ReviewItem | None: ...
    def get_pending(self) -> list[ReviewItem]: ...
    def get_all(self) -> list[ReviewItem]: ...
    def update(self, item: ReviewItem) -> None: ...


# ---------------------------------------------------------------------------
# Scraping protocols
# ---------------------------------------------------------------------------

class SourceScraper(Protocol):
    @property
    def source_id(self) -> str: ...
    async def scrape(self) -> tuple[list[RawStore], list[RawScrapedRecord]]: ...


# ---------------------------------------------------------------------------
# Normalization protocols
# ---------------------------------------------------------------------------

class NormalizationStep(Protocol):
    def apply(self, store_name: str, deal_description: str) -> tuple[str, str]:
        """Return (processed_store_name, processed_deal_description)."""
        ...


# ---------------------------------------------------------------------------
# Matching protocols
# ---------------------------------------------------------------------------

class MatchStage(Protocol):
    @property
    def name(self) -> str: ...

    def match(
        self,
        normalized: NormalizedRecord,
        aliases: list[StoreAlias],
        stores: list[CanonicalStore],
    ) -> MatchVerdict | None:
        """Return a verdict if this stage can decide, else None to continue."""
        ...
