import type { Language } from "./copy";
import en from "./voiceover-manifest.en.json";
import he from "./voiceover-manifest.he.json";

export type VoiceoverLine = {
  file: string;
  seconds: number;
  frames: number;
  startFrame: number;
  windowFrames: number;
};

export type VoiceoverManifest = {
  engine: string;
  language: string;
  voice: string;
  lines: Record<string, VoiceoverLine>;
};

/**
 * Generated by scripts/generate-voiceover.mjs. Both languages share the same
 * line ids and startFrames — only the take durations differ, which is why the
 * music ducking reads whichever manifest the composition is rendering.
 */
export const MANIFESTS: Record<Language, VoiceoverManifest> = {
  en: en as VoiceoverManifest,
  he: he as VoiceoverManifest,
};
