/** Shared Tailwind class strings — styling only, no runtime logic. */
export const fintech = {
  page: "fintech-page",
  card: "fintech-card",
  cardInset: "fintech-card-inset",
  metric: "fintech-metric",
  metricBlue: "fintech-metric fintech-metric-blue",
  metricViolet: "fintech-metric fintech-metric-violet",
  metricAmber: "fintech-metric fintech-metric-amber",
  metricEmerald: "fintech-metric fintech-metric-emerald",
  metricValue: "fintech-metric-value",
  metricLabel: "fintech-metric-label",
  amount: "fintech-amount",
  sectionTitle: "fintech-section-title",
  sectionEyebrow: "fintech-section-eyebrow",
  iconWrap: "fintech-icon-wrap",
  iconWrapBlue: "fintech-icon-wrap-blue",
  iconWrapViolet: "fintech-icon-wrap-violet",
  iconWrapAmber: "fintech-icon-wrap-amber",
  iconWrapEmerald: "fintech-icon-wrap-emerald",
  listRow: "fintech-list-row",
  listRowAccent: "fintech-list-row-accent",
  subheader: "fintech-subheader",
  statusConnected: "fintech-status-connected",
  input: "fintech-input",
  select: "fintech-select",
  rankBadge: "fintech-rank-badge",
  fitBadge: "fintech-fit-badge",
  gradientBanner: "fintech-gradient-banner",
} as const
